Added tests for the transactional risking local services
hmrc/transactional-risking-acceptance-tests pull request #1
Opened 2022-06-09 20:29 UTC by Krishnarepogit

2022-06-13 10:46 UTC, erasmos-hmrc commented
When I tried to run `run_tests.sh` , I received warnings about the formatting.

```
[warn] /Users/seanrasmussen/work/transactional-risking-acceptance-tests/src/test/scala/uk/gov/hmrc/test/api/helpers/IndividualsMatchingHelper.scala isn't formatted properly!
[warn] /Users/seanrasmussen/work/transactional-risking-acceptance-tests/src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala isn't formatted properly!
[warn] /Users/seanrasmussen/work/transactional-risking-acceptance-tests/src/test/scala/uk/gov/hmrc/test/api/service/IndividualsMatchingService.scala isn't formatted properly!
[warn] /Users/seanrasmussen/work/transactional-risking-acceptance-tests/src/test/scala/uk/gov/hmrc/test/api/helpers/TestDataHelper.scala isn't formatted properly!
[warn] /Users/seanrasmussen/work/transactional-risking-acceptance-tests/src/test/scala/uk/gov/hmrc/test/api/models/User.scala isn't formatted properly!
[warn] /Users/seanrasmussen/work/transactional-risking-acceptance-tests/src/test/scala/uk/gov/hmrc/test/api/models/IndividualsLinks.scala isn't formatted properly!
[error] 6 files must be formatted
[error] (Test / scalafmtCheck) 6 files must be formatted
[error] Total time: 6 s, completed 13 Jun 2022, 11:44:34
```

See the README for instructions.

2022-06-13 11:07 UTC, erasmos-hmrc requested changes
I'm open to having a call to go through this.

Additionally, I would suggest that you delete any files we no longer require.

2022-06-13 11:07 UTC, erasmos-hmrc commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
I don't believe we should have any commented out code, especially given the benefits of version control.

2022-06-13 11:07 UTC, erasmos-hmrc commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
> +    Scenario("Get transactional risking hello worl response") {
Typo: "worl".

2022-06-13 11:07 UTC, erasmos-hmrc commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
> +      Given("There is an existing transactional risking api")
We don't need a "given" section in this case, do we?

2022-06-13 11:07 UTC, erasmos-hmrc commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
> +      val individualsMatchId: Unit = testDataHelper.createAnIndividual(ninoUser)
Seems irrelevant.

2022-06-13 11:07 UTC, erasmos-hmrc commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
> +      def  transactionalrisking :String = testDataHelper.obtainMatchIdFromHref()
Seems irrelevant.

2022-06-13 11:07 UTC, erasmos-hmrc commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
> +      def createdUser : User = testDataHelper.createAnIndividual( ninoUser)
I know that the method calls the `hello-world` endpoint, so why does it have this name?

And I would have it return a `StandaloneWSRequest`, so that we can assert that the status is 200 and that the body is the string "Hello world".

2022-06-13 11:07 UTC, erasmos-hmrc commented on .bsp/sbt.json
> +{"name":"sbt","version":"1.5.8","bspVersion":"2.0.0-M5","languages":["scala"],"argv":["/Library/Java/JavaVirtualMachines/jdk-15.0.1.jdk/Contents/Home/bin/java","-Xms100m","-Xmx100m","-classpath","/Us
This file shouldn't be committed.

I'd suggest that you add an exclusion for that directory in the `.gitignore`.

2022-06-13 11:12 UTC, Krishnarepogit commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
> +      val individualsMatchId: Unit = testDataHelper.createAnIndividual(ninoUser)
This is the standard repo for the acceptance and those are very important in next level tests once it replace with auth... so need have with commented lines

2022-06-13 11:13 UTC, Krishnarepogit commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
> +      def  transactionalrisking :String = testDataHelper.obtainMatchIdFromHref()
theses all will same as the above comment for auth service which will be kept for reusability of the  code.. I prefer to keep as commented and use later ...

2022-06-13 11:21 UTC, Krishnarepogit commented on README.md
>      docker run --rm -d --name mongo -d -p 27017:27017 mongo:4.0
It a just readme file want keep the MDb commands ...

2022-06-13 11:30 UTC, Krishnarepogit commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
yes its will be changed to HelloWorldSpec

2022-06-13 13:23 UTC, erasmos-hmrc commented on README.md
>      docker run --rm -d --name mongo -d -p 27017:27017 mongo:4.0
The README file is misleading if it mentions Mongo.

Best to remove it.

2022-06-13 13:25 UTC, erasmos-hmrc commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
> +      val individualsMatchId: Unit = testDataHelper.createAnIndividual(ninoUser)
I'm afraid I disagree.

When needed, we can get that code from either the history of this repo, or [the template repo](https://github.com/hmrc/platform-example-api-scalatest-tests).

2022-06-13 13:25 UTC, erasmos-hmrc commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
> +      def  transactionalrisking :String = testDataHelper.obtainMatchIdFromHref()
I'm afraid I disagree.

When needed, we can get that code from either the history of this repo, or [the template repo](https://github.com/hmrc/platform-example-api-scalatest-tests).

2022-06-14 16:34 UTC, Krishnarepogit commented on README.md
>      docker run --rm -d --name mongo -d -p 27017:27017 mongo:4.0
yes agreed and removed all

2022-06-14 16:38 UTC, Krishnarepogit commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
> +    Scenario("Get transactional risking hello worl response") {
corrected

2022-06-14 16:39 UTC, Krishnarepogit commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
> +      Given("There is an existing transactional risking api")
removed code and keep the Gherkin format line

2022-06-14 16:40 UTC, Krishnarepogit commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
> +      def  transactionalrisking :String = testDataHelper.obtainMatchIdFromHref()
yes agreed and removed all for auth service code for post call

2022-06-14 16:40 UTC, Krishnarepogit commented on .bsp/sbt.json
> +{"name":"sbt","version":"1.5.8","bspVersion":"2.0.0-M5","languages":["scala"],"argv":["/Library/Java/JavaVirtualMachines/jdk-15.0.1.jdk/Contents/Home/bin/java","-Xms100m","-Xmx100m","-classpath","/Us
removed

2022-06-15 08:53 UTC, erasmos-hmrc commented
@Krishnarepogit : running `./run_tests.sh` fails because of Scala formatting.

2022-06-15 08:55 UTC, erasmos-hmrc commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
Confirmed.

2022-06-15 08:55 UTC, erasmos-hmrc commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
> +    Scenario("Get transactional risking hello worl response") {
Confirmed.

2022-06-15 08:56 UTC, erasmos-hmrc commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
> +      val individualsMatchId: Unit = testDataHelper.createAnIndividual(ninoUser)
Confirmed.

2022-06-15 08:59 UTC, erasmos-hmrc commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
> +      Given("There is an existing transactional risking api")
That section does nothing; would suggest you remove "Given".

2022-06-15 08:59 UTC, erasmos-hmrc commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
> +      def  transactionalrisking :String = testDataHelper.obtainMatchIdFromHref()
Confirmed.

2022-06-15 10:21 UTC, erasmos-hmrc commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
> +      Given("There is an existing transactional risking api")
I removed it.

2022-06-15 10:21 UTC, erasmos-hmrc commented on src/test/scala/uk/gov/hmrc/test/api/specs/ExampleSpec.scala
> +      def createdUser : User = testDataHelper.createAnIndividual( ninoUser)
I corrected it.

2022-06-15 10:35 UTC, erasmos-hmrc submitted a review, later dismissed

2022-06-15 10:49 UTC, erasmos-hmrc commented
@Krishnarepogit . As agreed, because none of your commits were [signed](https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?spaceKey=SEC&title=Adding+a+GitHub+Signing+Key), I will squash locally, and force push on to this branch.

2022-06-15 10:55 UTC, Krishnarepogit commented
Yes, I agree to the squash

2022-06-15 10:59 UTC, erasmos-hmrc approved these changes
This is just a squash.

2022-06-15 10:59 UTC, merged